version: '3.8'

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: health_db
    networks:
      - mongo-network
    command: --auth

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: 172.18.0.3
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://172.18.0.3:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    networks:
      - mongo-network
    depends_on:
      - mongodb
    links:
      - mongodb

# 使用说明：
# 1. 启动服务: docker-compose up -d
# 2. 停止服务: docker-compose down
# 3. 访问Mongo-Express: http://localhost:8081
# 4. MongoDB连接地址: mongodb://admin:admin123@localhost:27017